/** Client-safe domain constants, labels and formatters shared across modules. */

export type Severity = 'low' | 'moderate' | 'high' | 'extreme';
export const SEVERITIES: Severity[] = ['low', 'moderate', 'high', 'extreme'];

export const SEVERITY_META: Record<Severity, { label: string; short: string; description: string; rank: number }> = {
  low: { label: 'Low', short: 'LOW', description: 'Below CLIMATIQ heat-risk thresholds.', rank: 0 },
  moderate: {
    label: 'Moderate',
    short: 'MOD',
    description: 'Hot and above normal — approaching heatwave conditions (CLIMATIQ class).',
    rank: 1,
  },
  high: { label: 'High', short: 'HIGH', description: 'Meets IMD heatwave criteria (as evaluated by CLIMATIQ).', rank: 2 },
  extreme: {
    label: 'Extreme',
    short: 'EXT',
    description: 'Meets IMD severe-heatwave criteria (as evaluated by CLIMATIQ).',
    rank: 3,
  },
};

export function severityAtLeast(s: Severity, min: Severity) {
  return SEVERITY_META[s].rank >= SEVERITY_META[min].rank;
}

export type DataKind = 'observed' | 'reanalysis' | 'nwp_forecast' | 'model_forecast' | 'simulated';

export const DATA_KIND_META: Record<DataKind, { label: string; description: string }> = {
  observed: { label: 'Observed', description: 'Measured by a verified station or source.' },
  reanalysis: {
    label: 'Reanalysis',
    description: 'Model-based reconstruction of past weather (ERA5) — not a station measurement.',
  },
  nwp_forecast: { label: 'NWP guidance', description: 'Third-party numerical weather prediction (Open-Meteo).' },
  model_forecast: { label: 'CLIMATIQ forecast', description: 'Generated by the CLIMATIQ model — not an official forecast.' },
  simulated: { label: 'Simulated', description: 'Synthetic demo data — not a real measurement.' },
};

export type Confidence = 'low' | 'medium' | 'high';
export const CONFIDENCE_META: Record<Confidence, { label: string; description: string }> = {
  low: { label: 'Low confidence', description: 'Wide uncertainty band or limited inputs.' },
  medium: { label: 'Medium confidence', description: 'Moderate uncertainty band.' },
  high: { label: 'High confidence', description: 'Narrow uncertainty band and consistent inputs.' },
};

export const INCIDENT_STATUS_META = {
  reported: { label: 'Reported', order: 0 },
  triaged: { label: 'Triaged', order: 1 },
  in_progress: { label: 'In progress', order: 2 },
  monitoring: { label: 'Monitoring', order: 3 },
  resolved: { label: 'Resolved', order: 4 },
  closed: { label: 'Closed', order: 5 },
} as const;
export type IncidentStatus = keyof typeof INCIDENT_STATUS_META;

export const PRIORITY_META = {
  p1: { label: 'P1 · Critical' },
  p2: { label: 'P2 · High' },
  p3: { label: 'P3 · Medium' },
  p4: { label: 'P4 · Low' },
} as const;
export type Priority = keyof typeof PRIORITY_META;

export const AUDIENCE_META = {
  government: { label: 'Government & administration' },
  disaster_mgmt: { label: 'Disaster-management teams' },
  field_team: { label: 'Field response teams' },
  public: { label: 'General public' },
} as const;
export type Audience = keyof typeof AUDIENCE_META;

// ─────────── Formatting (India locale, IST) ───────────
const IST = 'Asia/Kolkata';

export function fmtTemp(c: number | null | undefined, digits = 1) {
  return c == null || Number.isNaN(c) ? '—' : `${c.toFixed(digits)} °C`;
}

export function fmtDelta(c: number | null | undefined, digits = 1) {
  if (c == null || Number.isNaN(c)) return '—';
  const s = c > 0 ? '+' : c < 0 ? '−' : '±';
  return `${s}${Math.abs(c).toFixed(digits)} °C`;
}

export function fmtDate(d: string | Date, opts: Intl.DateTimeFormatOptions = { day: 'numeric', month: 'short', year: 'numeric' }) {
  const date = typeof d === 'string' && /^\d{4}-\d{2}-\d{2}$/.test(d) ? new Date(`${d}T00:00:00+05:30`) : new Date(d);
  return date.toLocaleDateString('en-IN', { timeZone: IST, ...opts });
}

export function fmtDateTime(d: string | Date) {
  return new Date(d).toLocaleString('en-IN', { timeZone: IST, day: 'numeric', month: 'short', hour: '2-digit', minute: '2-digit' }) + ' IST';
}

export function fmtRelative(d: string | Date, now: Date = new Date()) {
  const diff = (new Date(d).getTime() - now.getTime()) / 1000;
  const abs = Math.abs(diff);
  const rtf = new Intl.RelativeTimeFormat('en-IN', { numeric: 'auto' });
  if (abs < 60) return rtf.format(Math.round(diff), 'second');
  if (abs < 3600) return rtf.format(Math.round(diff / 60), 'minute');
  if (abs < 86400) return rtf.format(Math.round(diff / 3600), 'hour');
  return rtf.format(Math.round(diff / 86400), 'day');
}

/** Today's date in IST as YYYY-MM-DD. */
export function todayIST(now: Date = new Date()) {
  return now.toLocaleDateString('en-CA', { timeZone: IST });
}

export function addDays(day: string, n: number) {
  const d = new Date(`${day}T00:00:00Z`);
  d.setUTCDate(d.getUTCDate() + n);
  return d.toISOString().slice(0, 10);
}
