import type { Metadata } from 'next';
import Link from 'next/link';
import { FlaskConical, Plus, RadioTower } from 'lucide-react';
import { EmptyState, LinkButton, PageHeader, Panel } from '@/components/ui/primitives';
import { DemoTag, ProvenanceBadge } from '@/components/ui/badges';
import { StationDot } from '@/components/map/station-dot';
import type { MapStation } from '@/components/map/types';
import { can } from '@/lib/rbac';
import { fmtDateTime, fmtRelative, fmtTemp } from '@/lib/domain';
import { requirePagePermission } from '@/server/auth/dal';
import { getDb } from '@/server/db/client';
import { listStations, statusSummary, type StationFilters } from '@/server/stations/queries';
import { OFFLINE_AFTER_MS, STALE_AFTER_MS, STATION_STATUS_META, STATION_TYPE_META, type StationStatus, type StationType } from '@/server/stations/status';
import { StationsMapLazy, StatusPill } from './station-ui';

export const metadata: Metadata = { title: 'Weather stations' };

const STATUSES: StationStatus[] = ['online', 'degraded', 'offline', 'planned'];
const TYPES: StationType[] = ['aws_simulated', 'iot'];

export default async function StationsPage({ searchParams }: PageProps<'/stations'>) {
  const user = await requirePagePermission('station:view');
  const sp = await searchParams;
  const filters: StationFilters = {
    status: STATUSES.includes(sp.status as StationStatus) ? (sp.status as StationStatus) : undefined,
    type: TYPES.includes(sp.type as StationType) ? (sp.type as StationType) : undefined,
    state: typeof sp.state === 'string' && /^IN-[A-Z]{2}$/.test(sp.state) ? sp.state : undefined,
  };
  const db = getDb();
  const all = await listStations(db);
  const stateOptions = [...new Map(all.map((s) => [s.stateCode, s.stateName])).entries()].map(([code, name]) => ({ code, name })).sort((a, b) => a.name.localeCompare(b.name));
  const stations = all.filter(
    (s) => (!filters.status || s.status === filters.status) && (!filters.type || s.stationType === filters.type) && (!filters.state || s.stateCode === filters.state),
  );
  const summary = statusSummary(all);
  const canManage = can(user.assignments, 'station:manage');
  const filtered = Boolean(filters.status || filters.type || filters.state);
  const mapStations: MapStation[] = stations.map((s) => ({
    code: s.code,
    name: s.name,
    lat: s.lat,
    lon: s.lon,
    status: s.status,
    stationType: s.stationType,
    isSimulated: s.isSimulated,
    lastSeenAt: s.lastSeenAt,
    latestTempC: s.latest?.tempC ?? null,
    latestAt: s.latest?.observedAt ?? null,
    regionName: s.regionName,
    stateCode: s.stateCode,
  }));

  return (
    <div className="flex flex-col gap-4">
      <PageHeader
        eyebrow="Weather stations"
        title="Station network"
        description="Automatic weather stations feeding CLIMATIQ. No physical hardware is deployed in this prototype: the demo network is simulated, and real IoT stations can be registered to push observations through the REST ingestion API."
        actions={
          canManage ? (
            <LinkButton href="/stations/register" size="sm">
              <Plus className="size-4" aria-hidden /> Register IoT station
            </LinkButton>
          ) : undefined
        }
      />

      {summary.simulated > 0 && (
        <div className="flex gap-3 rounded-2xl border border-dashed p-3 text-sm" style={{ borderColor: 'var(--prov-simulated)' }} role="note">
          <FlaskConical className="mt-0.5 size-5 shrink-0" style={{ color: 'var(--prov-simulated)' }} aria-hidden />
          <p className="text-fg-muted">
            <strong className="text-fg">{summary.simulated} of {summary.total} stations are SIMULATED.</strong> Their hourly observations are synthetic values generated by
            the CLIMATIQ demo simulator (anchored to ERA5 reanalysis of the district where available) and are never mixed with real measurements.
            {summary.real > 0 ? ` ${summary.real} registered IoT station(s) report real but unverified data.` : ' No real station has reported yet.'}
          </p>
        </div>
      )}

      <section aria-label="Status summary" className="grid grid-cols-2 gap-3 sm:grid-cols-4 lg:grid-cols-6">
        {STATUSES.map((s) => (
          <Link
            key={s}
            href={filters.status === s ? '/stations' : `/stations?status=${s}`}
            aria-current={filters.status === s ? 'true' : undefined}
            className="glass flex flex-col gap-1 rounded-2xl px-3.5 py-3 transition hover:bg-glass-strong aria-[current]:ring-2 aria-[current]:ring-accent/40"
            title={STATION_STATUS_META[s].description}
          >
            <span className="flex items-center gap-1.5 text-[10px] font-semibold uppercase tracking-[0.14em] text-fg-subtle">
              <StationDot status={s} size={10} /> {STATION_STATUS_META[s].label}
            </span>
            <span className="font-display text-2xl font-bold tabular">{summary.byStatus[s]}</span>
          </Link>
        ))}
        <div className="glass flex flex-col gap-1 rounded-2xl px-3.5 py-3">
          <span className="text-[10px] font-semibold uppercase tracking-[0.14em] text-fg-subtle">Simulated</span>
          <span className="font-display text-2xl font-bold tabular">{summary.simulated}</span>
        </div>
        <div className="glass flex flex-col gap-1 rounded-2xl px-3.5 py-3">
          <span className="text-[10px] font-semibold uppercase tracking-[0.14em] text-fg-subtle">IoT (real)</span>
          <span className="font-display text-2xl font-bold tabular">{summary.real}</span>
        </div>
      </section>

      <form method="get" className="glass flex flex-wrap items-end gap-3 rounded-2xl px-4 py-3" aria-label="Filter stations">
        <FilterSelect id="f-status" name="status" label="Status" value={filters.status} options={STATUSES.map((s) => [s, STATION_STATUS_META[s].label])} />
        <FilterSelect id="f-type" name="type" label="Type" value={filters.type} options={TYPES.map((t) => [t, STATION_TYPE_META[t].label])} />
        <FilterSelect id="f-state" name="state" label="State" value={filters.state} options={stateOptions.map((o) => [o.code, o.name])} />
        <button type="submit" className="h-9 rounded-xl bg-wine px-4 text-sm font-medium text-sand hover:bg-wine-600 dark:bg-accent dark:text-accent-fg">
          Apply
        </button>
        {filtered && (
          <Link href="/stations" className="h-9 content-center text-sm text-fg-muted underline-offset-2 hover:underline">
            Clear filters
          </Link>
        )}
        <p className="basis-full text-[11px] text-fg-subtle sm:ml-auto sm:basis-auto">
          Status reflects freshness: no report for {STALE_AFTER_MS / 3_600_000} h → degraded, {OFFLINE_AFTER_MS / 3_600_000} h → offline.
        </p>
      </form>

      <div className="grid grid-cols-[minmax(0,1fr)] gap-4 xl:grid-cols-[minmax(0,1fr)_minmax(0,1.35fr)]" data-tour="stations">
        <Panel title="Station map" description={`${stations.length} station${stations.length === 1 ? '' : 's'} shown`} bodyClassName="p-0" className="overflow-hidden">
          <div className="h-[420px] xl:h-[560px]">
            <StationsMapLazy stations={mapStations} />
          </div>
        </Panel>

        <Panel
          title="Stations"
          description="Latest observation, freshness and provenance"
          bodyClassName="px-0 pb-2 pt-1"
          footer={
            <span className="flex flex-wrap items-center gap-2">
              <ProvenanceBadge kind="simulated" source="CLIMATIQ demo simulator" />
              <ProvenanceBadge kind="observed" source="IoT stations · unverified" />
              <span>Timestamps in IST.</span>
            </span>
          }
        >
          {stations.length === 0 ? (
            <div className="px-5 py-4">
              <EmptyState title={all.length ? 'No station matches these filters' : 'No stations registered'}>
                {all.length ? <Link href="/stations">Clear the filters</Link> : 'Register an IoT station or run the demo seed.'}
              </EmptyState>
            </div>
          ) : (
            <div className="overflow-x-auto">
              <table className="w-full min-w-[640px] text-left text-sm">
                <caption className="sr-only">Weather stations with status, last report and latest temperature</caption>
                <thead className="text-[11px] uppercase tracking-wide text-fg-subtle">
                  <tr>
                    <th scope="col" className="px-5 py-2">Station</th>
                    <th scope="col" className="px-3 py-2">Region</th>
                    <th scope="col" className="px-3 py-2">Status</th>
                    <th scope="col" className="px-3 py-2">Last seen</th>
                    <th scope="col" className="px-5 py-2 text-right">Latest temp</th>
                  </tr>
                </thead>
                <tbody>
                  {stations.map((s) => (
                    <tr key={s.code} className="border-t border-line align-top">
                      <th scope="row" className="px-5 py-2.5 font-normal">
                        <Link href={`/stations/${s.code}`} className="font-medium text-fg hover:underline">
                          {s.name}
                        </Link>
                        <span className="mt-0.5 flex flex-wrap items-center gap-1.5">
                          <span className="font-mono text-[11px] text-fg-subtle">{s.code}</span>
                          {s.isSimulated ? (
                            <DemoTag label="Simulated" />
                          ) : (
                            <span className="inline-flex items-center gap-1 rounded-md border border-line-strong px-1.5 text-[10px] font-semibold uppercase tracking-wide text-fg-muted">
                              <RadioTower className="size-3" aria-hidden /> IoT
                            </span>
                          )}
                        </span>
                      </th>
                      <td className="px-3 py-2.5 text-xs text-fg-muted">
                        {s.regionName}
                        {s.regionCode !== s.stateCode && <span className="block text-fg-subtle">{s.stateName}</span>}
                      </td>
                      <td className="px-3 py-2.5">
                        <StatusPill status={s.status} />
                      </td>
                      <td className="px-3 py-2.5 text-xs text-fg-muted" title={s.lastSeenAt ? fmtDateTime(s.lastSeenAt) : undefined}>
                        {s.lastSeenAt ? fmtRelative(s.lastSeenAt) : 'Never'}
                      </td>
                      <td className="px-5 py-2.5 text-right text-xs">
                        {s.latest?.tempC != null ? (
                          <>
                            <span className="tabular font-medium text-fg">{fmtTemp(s.latest.tempC)}</span>
                            <span className="block text-[10px] uppercase tracking-wide text-fg-subtle">
                              {s.latest.dataKind === 'simulated' ? 'simulated' : s.latest.quality}
                            </span>
                          </>
                        ) : (
                          <span className="text-fg-subtle">—</span>
                        )}
                      </td>
                    </tr>
                  ))}
                </tbody>
              </table>
            </div>
          )}
        </Panel>
      </div>

      <Panel title="Connect a real IoT station" description="REST ingestion for future hardware">
        <p className="text-sm text-fg-muted">
          Registered IoT stations push observations with <code className="rounded bg-accent-soft px-1 font-mono text-xs">POST /api/v1/stations/&#123;code&#125;/observations</code> using
          their own API key (<code className="font-mono text-xs">Authorization: Bearer …</code>). Payloads are validated, plausibility-checked (sudden jumps are flagged
          “suspect”), de-duplicated per timestamp and stored as <em>unverified</em> — never auto-verified. See <code className="font-mono text-xs">docs/API.md</code> →
          “Stations &amp; IoT ingestion”.
        </p>
      </Panel>
    </div>
  );
}

function FilterSelect({ id, name, label, value, options }: { id: string; name: string; label: string; value?: string; options: [string, string][] }) {
  return (
    <div className="flex min-w-36 flex-col gap-1">
      <label htmlFor={id} className="text-xs font-semibold text-fg-muted">
        {label}
      </label>
      <select id={id} name={name} defaultValue={value ?? ''} className="h-9 rounded-xl border border-line-strong bg-glass-strong px-2 text-sm text-fg">
        <option value="">All</option>
        {options.map(([v, l]) => (
          <option key={v} value={v}>
            {l}
          </option>
        ))}
      </select>
    </div>
  );
}
