/**
 * Stateless "generate → preview → save draft" flow: the generated preview is returned to the browser together with an
 * HMAC signature (SESSION_SECRET). Saving re-verifies the signature, so the stored draft is exactly what the server
 * generated (the client cannot alter content, provenance or the input bundle).
 */
import { createHmac, timingSafeEqual } from 'node:crypto';
import { env } from '../config/env';
import { DomainError } from '../alerts/errors';

const MAX_AGE_MS = 60 * 60 * 1000;

function sign(data: string, secret: string) {
  return createHmac('sha256', secret).update(data).digest('base64url');
}

export function signPreview<T extends object>(userId: string, payload: T, secret = env().SESSION_SECRET): string {
  const body = Buffer.from(JSON.stringify({ v: 1, uid: userId, iat: Date.now(), payload })).toString('base64url');
  return `${body}.${sign(`advisory-preview:${body}`, secret)}`;
}

export function verifyPreview<T>(token: string, userId: string, secret = env().SESSION_SECRET): T {
  const [body, sig] = token.split('.');
  if (!body || !sig) throw new DomainError(400, 'Malformed preview token');
  const expected = Buffer.from(sign(`advisory-preview:${body}`, secret));
  const given = Buffer.from(sig);
  if (expected.length !== given.length || !timingSafeEqual(expected, given)) throw new DomainError(400, 'Preview signature is invalid — generate the advisory again');
  const decoded = JSON.parse(Buffer.from(body, 'base64url').toString('utf8')) as { v: number; uid: string; iat: number; payload: T };
  if (decoded.uid !== userId) throw new DomainError(403, 'This preview was generated by another user');
  if (Date.now() - decoded.iat > MAX_AGE_MS) throw new DomainError(410, 'Preview expired — generate the advisory again');
  return decoded.payload;
}
