import Link from 'next/link';
import { ExternalLink } from 'lucide-react';
import { LogoMark, Wordmark } from '@/components/shell/logo';

export function PublicHeader() {
  return (
    <header className="glass sticky top-3 z-30 mx-3 mt-3 flex min-w-0 items-center gap-2 rounded-2xl px-3 py-2.5 sm:gap-3 sm:px-4">
      <Link href="/" className="flex items-center gap-2 text-accent" aria-label="CLIMATIQ home">
        <LogoMark className="size-7" />
        <Wordmark className="hidden text-fg min-[420px]:inline" />
      </Link>
      <span className="hidden rounded-md bg-accent-soft px-2 py-0.5 text-[11px] font-semibold uppercase tracking-wider text-accent sm:inline">Public climate portal</span>
      <nav aria-label="Public" className="ml-auto flex shrink-0 items-center gap-0.5 text-xs sm:gap-1 sm:text-sm">
        <Link href="/portal" className="rounded-lg px-2 py-1.5 text-fg-muted hover:bg-accent-soft hover:text-fg sm:px-3">
          Outlook
        </Link>
        <Link href="/methodology" className="rounded-lg px-2 py-1.5 text-fg-muted hover:bg-accent-soft hover:text-fg sm:px-3">
          Methodology
        </Link>
        <Link href="/login" className="rounded-lg px-2 py-1.5 font-semibold text-accent hover:bg-accent-soft sm:px-3">
          Sign in
        </Link>
      </nav>
    </header>
  );
}

export function PublicFooter() {
  return (
    <footer className="mx-auto mt-16 max-w-6xl border-t border-line px-4 py-8 text-xs text-fg-muted">
      <p className="font-semibold text-fg">CLIMATIQ is a prototype decision-support tool — not an official warning service.</p>
      <p className="mt-1">
        For official heatwave warnings always follow the India Meteorological Department{' '}
        <a className="inline-flex items-center gap-0.5 font-medium text-accent hover:underline" href="https://mausam.imd.gov.in" target="_blank" rel="noreferrer">
          mausam.imd.gov.in <ExternalLink className="size-3" aria-hidden />
        </a>{' '}
        and your State/District Disaster Management Authority.
      </p>
      <ul className="mt-4 grid gap-1 sm:grid-cols-2">
        <li>
          Weather data by{' '}
          <a className="underline" href="https://open-meteo.com/" target="_blank" rel="noreferrer">
            Open-Meteo.com
          </a>{' '}
          (CC BY 4.0) · contains modified Copernicus Climate Change Service information (ERA5)
        </li>
        <li>Boundaries: geoBoundaries (CC BY 2.5 IN / ODbL) — simplified, not authenticated by the Survey of India</li>
        <li>Places © GeoNames (CC BY 4.0)</li>
        <li>Forecasts and advisories on this page are generated by CLIMATIQ models — see the methodology for limitations</li>
      </ul>
    </footer>
  );
}
