/**
 * Station status helpers (pure, no DB access).
 *
 * The stored `status` is what the station (or the seed/simulator) last reported. What we DISPLAY is an
 * "effective" status that also accounts for freshness: a station that has not reported for a while cannot be
 * considered online, whatever its stored status says.
 */
export type StationStatus = 'online' | 'degraded' | 'offline' | 'planned';
export type StationType = 'aws_simulated' | 'iot' | 'external';

/** No report for longer than this → an "online" station is shown as degraded. */
export const STALE_AFTER_MS = 3 * 3_600_000;
/** No report for longer than this → shown as offline. */
export const OFFLINE_AFTER_MS = 24 * 3_600_000;

export function effectiveStatus(stored: StationStatus, lastSeenAt: Date | string | null, now: Date = new Date()): StationStatus {
  if (!lastSeenAt) return stored === 'planned' ? 'planned' : 'offline';
  const age = now.getTime() - new Date(lastSeenAt).getTime();
  if (age > OFFLINE_AFTER_MS) return 'offline';
  if (stored === 'planned') return 'online';
  if (stored === 'online' && age > STALE_AFTER_MS) return 'degraded';
  return stored;
}

export const STATION_STATUS_META: Record<StationStatus, { label: string; description: string }> = {
  online: { label: 'Online', description: 'Reported within the last 3 hours.' },
  degraded: { label: 'Degraded', description: 'Reporting with gaps, missing sensors or delayed data.' },
  offline: { label: 'Offline', description: 'No report for more than 24 hours.' },
  planned: { label: 'Planned', description: 'Registered but has not reported yet.' },
};

export const STATION_TYPE_META: Record<StationType, { label: string; description: string }> = {
  aws_simulated: {
    label: 'Simulated AWS',
    description: 'Demo automatic weather station. No physical hardware: observations are generated by the CLIMATIQ simulator.',
  },
  iot: { label: 'IoT station', description: 'Registered IoT station that pushes observations to the REST ingestion API.' },
  external: { label: 'External network', description: 'Station from an external network.' },
};

export function countByStatus(rows: { status: StationStatus }[]) {
  const out: Record<StationStatus, number> = { online: 0, degraded: 0, offline: 0, planned: 0 };
  for (const r of rows) out[r.status] += 1;
  return out;
}
