import type { Metadata } from 'next';
import Link from 'next/link';
import { notFound } from 'next/navigation';
import { ArrowLeft, FlaskConical, MapPin, RadioTower } from 'lucide-react';
import { EmptyState, PageHeader, Panel } from '@/components/ui/primitives';
import { DemoTag, ProvenanceBadge } from '@/components/ui/badges';
import type { MapStation } from '@/components/map/types';
import { can } from '@/lib/rbac';
import { fmtDateTime, fmtRelative, fmtTemp } from '@/lib/domain';
import { regionPath, requirePagePermission } from '@/server/auth/dal';
import { getDb } from '@/server/db/client';
import { getStation, stationObservationsBetween } from '@/server/stations/queries';
import { STATION_STATUS_META, STATION_TYPE_META } from '@/server/stations/status';
import { StationsMapLazy, StatusPill } from '../station-ui';
import { KeyRotation } from './key-rotation';
import { TrendCharts, type TrendPoint } from './trend-charts';

export async function generateMetadata({ params }: PageProps<'/stations/[code]'>): Promise<Metadata> {
  const { code } = await params;
  return { title: `Station ${decodeURIComponent(code)}` };
}

const HISTORY_ROWS = 72;

export default async function StationDetailPage({ params }: PageProps<'/stations/[code]'>) {
  const user = await requirePagePermission('station:view');
  const { code: raw } = await params;
  const code = decodeURIComponent(raw).toUpperCase();
  if (!/^[A-Z0-9-]{3,40}$/.test(code)) notFound();
  const db = getDb();
  const now = new Date();
  const s = await getStation(db, code, now);
  if (!s) notFound();

  const obs = await stationObservationsBetween(db, s.id, { from: new Date(now.getTime() - 7 * 86_400_000), to: now, order: 'asc' });
  const points: TrendPoint[] = obs.map((o) => ({ t: new Date(o.observedAt).getTime(), temp: o.tempC, rh: o.humidityPct, suspect: o.quality === 'suspect' }));
  const history = [...obs].reverse().slice(0, HISTORY_ROWS);
  const path = await regionPath(s.regionId);
  const canManage = s.stationType === 'iot' && can(user.assignments, 'station:manage', path);
  const sim = s.isSimulated;
  const kind = sim ? 'simulated' : 'observed';
  const latest = s.latest;
  const mapStation: MapStation = {
    code: s.code,
    name: s.name,
    lat: s.lat,
    lon: s.lon,
    status: s.status,
    stationType: s.stationType,
    isSimulated: s.isSimulated,
    lastSeenAt: s.lastSeenAt,
    latestTempC: latest?.tempC ?? null,
    latestAt: latest?.observedAt ?? null,
    regionName: s.regionName,
    stateCode: s.stateCode,
  };

  return (
    <div className="flex flex-col gap-4">
      <Link href="/stations" className="inline-flex w-fit items-center gap-1 text-xs text-fg-muted hover:text-fg hover:underline">
        <ArrowLeft className="size-3.5" aria-hidden /> All stations
      </Link>
      <PageHeader
        eyebrow={sim ? 'Simulated demo station' : STATION_TYPE_META[s.stationType].label}
        title={s.name}
        description={
          <>
            <span className="font-mono">{s.code}</span> · {s.regionName}
            {s.regionCode !== s.stateCode ? `, ${s.stateName}` : ''} ·{' '}
            <Link href={`/command?region=${s.regionCode}`} className="underline-offset-2 hover:underline">
              view on command map
            </Link>
          </>
        }
        actions={
          <>
            <StatusPill status={s.status} />
            {sim ? (
              <DemoTag label="Simulated" />
            ) : (
              <span className="inline-flex items-center gap-1 rounded-md border border-line-strong px-2 py-0.5 text-[11px] font-semibold uppercase tracking-wide text-fg-muted">
                <RadioTower className="size-3" aria-hidden /> IoT station
              </span>
            )}
          </>
        }
      />

      {sim && (
        <div className="flex gap-3 rounded-2xl border border-dashed p-3 text-sm" style={{ borderColor: 'var(--prov-simulated)' }} role="note">
          <FlaskConical className="mt-0.5 size-5 shrink-0" style={{ color: 'var(--prov-simulated)' }} aria-hidden />
          <p className="text-fg-muted">
            <strong className="text-fg">This is not a real weather station.</strong> There is no hardware at this location; all values below are synthetic, generated by
            the CLIMATIQ demo simulator from a diurnal curve anchored to ERA5 reanalysis of {s.regionName} (or a documented climatology where none exists). Do not use them
            for decisions.
          </p>
        </div>
      )}

      <div className="grid gap-4 lg:grid-cols-3">
        <Panel title="Latest observation" footer={<ProvenanceBadge kind={kind} source={s.sourceName} updated={latest ? fmtDateTime(latest.observedAt) : undefined} />}>
          {latest ? (
            <dl className="grid grid-cols-2 gap-3">
              <Metric label="Temperature" value={fmtTemp(latest.tempC)} />
              <Metric label="Humidity" value={latest.humidityPct == null ? '—' : `${latest.humidityPct.toFixed(0)} %`} />
              <Metric label="Wind" value={latest.windKmh == null ? '—' : `${latest.windKmh.toFixed(1)} km/h`} />
              <Metric label={sim ? 'Pressure (MSL-equiv.)' : 'Pressure'} value={latest.pressureHpa == null ? '—' : `${latest.pressureHpa.toFixed(1)} hPa`} />
              <div className="col-span-2 text-xs text-fg-muted">
                Observed {fmtRelative(latest.observedAt)} · quality <strong className="text-fg">{sim ? 'simulated' : latest.quality}</strong>
                {!sim && latest.quality !== 'verified' && ' (not yet reviewed — CLIMATIQ never auto-verifies IoT data)'}
              </div>
            </dl>
          ) : (
            <EmptyState title="No observations yet">{s.stationType === 'iot' ? 'This station has not sent data. Use its API key with the ingestion endpoint.' : 'No data stored.'}</EmptyState>
          )}
        </Panel>

        <Panel title="Status & freshness">
          <dl className="grid grid-cols-2 gap-x-3 gap-y-2.5 text-sm">
            <dt className="text-fg-muted">Status</dt>
            <dd>
              <StatusPill status={s.status} />
            </dd>
            <dt className="text-fg-muted">Last report</dt>
            <dd title={s.lastSeenAt ? fmtDateTime(s.lastSeenAt) : undefined}>{s.lastSeenAt ? fmtRelative(s.lastSeenAt) : 'Never'}</dd>
            <dt className="text-fg-muted">Reports (24 h)</dt>
            <dd className="tabular">{s.stats.last24h} / 24 expected</dd>
            <dt className="text-fg-muted">Reports (7 d)</dt>
            <dd className="tabular">{s.stats.last7d} / 168 expected</dd>
            <dt className="text-fg-muted">Suspect (7 d)</dt>
            <dd className="tabular">{s.stats.suspect7d}</dd>
            {s.storedStatus !== s.status && (
              <dd className="col-span-2 text-xs text-fg-muted">
                Last reported state was “{STATION_STATUS_META[s.storedStatus].label}”; shown as {STATION_STATUS_META[s.status].label.toLowerCase()} because of report age.
              </dd>
            )}
            {sim && s.status === 'offline' && (
              <dd className="col-span-2 text-xs text-fg-muted">Simulated observations were generated when the demo data was seeded; a demo reset regenerates them.</dd>
            )}
          </dl>
        </Panel>

        <Panel title="Station details">
          <dl className="grid grid-cols-2 gap-x-3 gap-y-2.5 text-sm">
            <dt className="text-fg-muted">Type</dt>
            <dd>{STATION_TYPE_META[s.stationType].label}</dd>
            <dt className="text-fg-muted">Source</dt>
            <dd>{s.sourceName}</dd>
            <dt className="text-fg-muted">Sensors</dt>
            <dd className="capitalize">{s.sensors.join(', ') || '—'}</dd>
            <dt className="text-fg-muted">Location</dt>
            <dd className="tabular">
              <MapPin className="mr-1 inline size-3.5 text-fg-subtle" aria-hidden />
              {s.lat.toFixed(4)}° N, {s.lon.toFixed(4)}° E
            </dd>
            <dt className="text-fg-muted">Elevation</dt>
            <dd>{s.elevationM == null ? (sim ? 'n/a (no physical site)' : 'not provided') : `${s.elevationM} m`}</dd>
            <dt className="text-fg-muted">Registered</dt>
            <dd>{fmtDateTime(s.registeredAt)}</dd>
          </dl>
        </Panel>
      </div>

      <div className="grid gap-4 lg:grid-cols-[minmax(0,1.6fr)_minmax(0,1fr)]">
        <Panel
          title="7-day trend"
          description="Hourly reports; breaks in the line are missing reports"
          footer={
            <span className="flex flex-wrap items-center gap-2">
              <ProvenanceBadge kind={kind} source={sim ? 'CLIMATIQ demo simulator — synthetic' : 'IoT observations · unverified'} />
              <span>Times in IST.</span>
            </span>
          }
        >
          {points.length ? <TrendCharts points={points} /> : <EmptyState title="No observations in the last 7 days" />}
        </Panel>
        <Panel title="Location" bodyClassName="p-0" className="overflow-hidden">
          <div className="h-[340px]">
            <StationsMapLazy stations={[mapStation]} single ariaLabel={`Location of ${s.name}`} />
          </div>
        </Panel>
      </div>

      {canManage && (
        <Panel title="API access" description="For the device that sends this station's observations">
          <div className="grid gap-4 md:grid-cols-2">
            <div className="text-xs text-fg-muted">
              <p className="mb-1.5">Send observations (single object or up to 500 in an array):</p>
              <pre className="overflow-x-auto rounded-xl bg-accent-soft p-3 font-mono text-[11px] text-fg">{`curl -X POST ${'$'}APP_URL/api/v1/stations/${s.code}/observations \\
  -H "Authorization: Bearer <station key>" \\
  -H "Content-Type: application/json" \\
  -d '{"observedAt":"2026-05-26T14:00:00+05:30","tempC":44.2,"humidityPct":18}'`}</pre>
            </div>
            <KeyRotation code={s.code} />
          </div>
        </Panel>
      )}

      <Panel
        title="Observation history"
        description={`Latest ${Math.min(HISTORY_ROWS, history.length)} reports of the last 7 days (newest first). Full range via GET /api/v1/stations/${s.code}/observations.`}
        bodyClassName="px-0 pb-2 pt-1"
      >
        {history.length === 0 ? (
          <div className="px-5">
            <EmptyState title="No observations recorded" />
          </div>
        ) : (
          <div className="max-h-[480px] overflow-auto">
            <table className="w-full min-w-[620px] text-left text-sm">
              <caption className="sr-only">Observation history of {s.name}</caption>
              <thead className="sticky top-0 bg-bg-elevated text-[11px] uppercase tracking-wide text-fg-subtle">
                <tr>
                  <th scope="col" className="px-5 py-2">Observed (IST)</th>
                  <th scope="col" className="px-3 py-2 text-right">Temp</th>
                  <th scope="col" className="px-3 py-2 text-right">RH</th>
                  <th scope="col" className="px-3 py-2 text-right">Wind</th>
                  <th scope="col" className="px-3 py-2 text-right">Pressure</th>
                  <th scope="col" className="px-5 py-2">Kind / quality</th>
                </tr>
              </thead>
              <tbody>
                {history.map((o) => (
                  <tr key={o.observedAt} className="border-t border-line">
                    <td className="px-5 py-1.5 text-xs">{fmtDateTime(o.observedAt)}</td>
                    <td className="px-3 py-1.5 text-right tabular">{fmtTemp(o.tempC)}</td>
                    <td className="px-3 py-1.5 text-right tabular">{o.humidityPct == null ? '—' : `${o.humidityPct.toFixed(0)} %`}</td>
                    <td className="px-3 py-1.5 text-right tabular">{o.windKmh == null ? '—' : `${o.windKmh.toFixed(1)} km/h`}</td>
                    <td className="px-3 py-1.5 text-right tabular">{o.pressureHpa == null ? '—' : `${o.pressureHpa.toFixed(1)} hPa`}</td>
                    <td className="px-5 py-1.5 text-xs">
                      <span className={o.quality === 'suspect' ? 'font-semibold text-accent' : 'text-fg-muted'}>
                        {o.dataKind === 'simulated' ? 'simulated' : o.dataKind} · {o.quality}
                      </span>
                    </td>
                  </tr>
                ))}
              </tbody>
            </table>
          </div>
        )}
      </Panel>
    </div>
  );
}

function Metric({ label, value }: { label: string; value: string }) {
  return (
    <div>
      <dt className="text-xs text-fg-muted">{label}</dt>
      <dd className="font-display text-xl font-bold tabular text-fg">{value}</dd>
    </div>
  );
}
