#!/usr/bin/env node
/**
 * One-command local development:
 *   1. creates .env.local with safe local defaults on first run (random SESSION_SECRET, DEMO_MODE=true)
 *   2. starts an embedded PostgreSQL 18 (data in .data/pg) unless DATABASE_URL points elsewhere
 *   3. applies migrations and the idempotent demo seed
 *   4. runs `next dev` on port 3100 (override with PORT)
 */
import { spawn, spawnSync } from 'node:child_process';
import { randomBytes } from 'node:crypto';
import { existsSync, mkdirSync, readFileSync, writeFileSync } from 'node:fs';
import { join } from 'node:path';

const root = process.cwd();
const envFile = join(root, '.env.local');
const PG_PORT = Number(process.env.EMBEDDED_PG_PORT ?? 54330);
const EMBEDDED_URL = `postgres://postgres:postgres@localhost:${PG_PORT}/climatiq`;

function parseEnv(text) {
  const out = {};
  for (const line of text.split(/\r?\n/)) {
    const m = line.match(/^\s*([A-Z0-9_]+)\s*=\s*(.*)\s*$/);
    if (m) out[m[1]] = m[2].replace(/^"(.*)"$/, '$1');
  }
  return out;
}

if (!existsSync(envFile)) {
  writeFileSync(
    envFile,
    [
      '# Generated by scripts/dev.mjs for local development. Not committed (see .gitignore).',
      `DATABASE_URL=${EMBEDDED_URL}`,
      `SESSION_SECRET=${randomBytes(32).toString('hex')}`,
      'DEMO_MODE=true',
      'APP_URL=http://localhost:3100',
      'AI_PROVIDER=template',
      '# GEMINI_API_KEY=',
      '# ANTHROPIC_API_KEY=',
      '',
    ].join('\n'),
  );
  console.log('› Created .env.local with local defaults');
}

const fileEnv = parseEnv(readFileSync(envFile, 'utf8'));
const merged = { ...fileEnv, ...process.env };
const useEmbedded = (merged.DATABASE_URL ?? EMBEDDED_URL) === EMBEDDED_URL;

let pg;
if (useEmbedded) {
  const { default: EmbeddedPostgres } = await import('embedded-postgres');
  const dataDir = join(root, '.data', 'pg');
  const fresh = !existsSync(join(dataDir, 'PG_VERSION'));
  mkdirSync(join(root, '.data'), { recursive: true });
  pg = new EmbeddedPostgres({
    databaseDir: dataDir,
    user: 'postgres',
    password: 'postgres',
    port: PG_PORT,
    persistent: true,
    initdbFlags: ['--encoding=UTF8', '--locale=C'],
    onLog: () => {},
  });
  if (fresh) {
    console.log('› Initialising embedded PostgreSQL cluster in .data/pg …');
    await pg.initialise();
  }
  await pg.start();
  try {
    await pg.createDatabase('climatiq');
  } catch {
    /* already exists */
  }
  console.log(`› Embedded PostgreSQL running on port ${PG_PORT}`);
}

const childEnv = { ...merged, DATABASE_URL: merged.DATABASE_URL ?? EMBEDDED_URL };

const setup = spawnSync(process.execPath, ['--import', 'tsx', 'scripts/db-setup.ts'], {
  stdio: 'inherit',
  env: childEnv,
});
if (setup.status !== 0) {
  console.error('✗ Database setup failed');
  if (pg) await pg.stop();
  process.exit(1);
}

const port = process.env.PORT ?? '3100';
const nextBin = join(root, 'node_modules', 'next', 'dist', 'bin', 'next');
const next = spawn(process.execPath, [nextBin, 'dev', '-p', port], { stdio: 'inherit', env: childEnv });

let stopping = false;
async function shutdown(code = 0) {
  if (stopping) return;
  stopping = true;
  next.kill();
  if (pg) await pg.stop().catch(() => {});
  process.exit(code);
}
process.on('SIGINT', () => shutdown(0));
process.on('SIGTERM', () => shutdown(0));
next.on('exit', (code) => shutdown(code ?? 0));
